name: lt_goat_farm
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter/services.dart:
  datetime_picker_formfield: ^1.0.0
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^9.1.2
  assets:
    - assets/
dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.0.8
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  image_picker: ^0.8.4+4
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

 